version: '3.8'

services:
  social-media-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      - db
    environment:
      UV_THREADPOOL_SIZE: 128
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
  db-migration:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run db:migration
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: social-media-user
      POSTGRES_PASSWORD: password123!
      PGPASSWORD: password123!
      POSTGRES_DB: social-media
    healthcheck:
      test: ['CMD', '/health-check.sh', 'social-media', 'social-media-user', 'password123!']
      interval: 15s
      timeout: 10s
      retries: 20
    ports:
      - '15432:5432'
    volumes:
      - ./db/health-check.sh:/health-check.sh
      - ./db/postgresql.conf:/etc/postgresql.conf
    tmpfs:
      - /var/lib/postgresql/data
